version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "9091:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./buddyboss-timeline_files:/usr/share/nginx/html/buddyboss-timeline_files
      - ./fonts:/usr/share/nginx/html/fonts
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 